version: '3'

services:
  web:
    image: captaction-php
    ports:
      - '8090:8000'
    volumes:
      - ./:/app
    command: php artisan serve --host=0.0.0.0
    links:
      - mysql
      - mailtrap

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - mysql-data:/var/lib/mysql
    
  mailtrap:
    image: eaudeweb/mailtrap
    ports:
      - '8086:80'

volumes:
  mysql-data: